/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RoomIdImport } from './routes/$roomId'

// Create/Update Routes

const RoomIdRoute = RoomIdImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$roomId': {
      id: '/$roomId'
      path: '/$roomId'
      fullPath: '/$roomId'
      preLoaderRoute: typeof RoomIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/$roomId': typeof RoomIdRoute
}

export interface FileRoutesByTo {
  '/$roomId': typeof RoomIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/$roomId': typeof RoomIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to: '/$roomId'
  id: '__root__' | '/$roomId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  RoomIdRoute: typeof RoomIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  RoomIdRoute: RoomIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/$roomId"
      ]
    },
    "/$roomId": {
      "filePath": "$roomId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
