/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UnprojectImport } from './routes/unproject'
import { Route as Undistort2Import } from './routes/undistort2'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as SetupIndexImport } from './routes/setup/index'
import { Route as VisualizeVisualizeCommandsImport } from './routes/visualize/VisualizeCommands'
import { Route as Visualize2DViewImport } from './routes/visualize/2DView'
import { Route as SetupUrlEntryImport } from './routes/setup.url-entry'
import { Route as SetupSetupImport } from './routes/setup/setup'
import { Route as SetupPointSelectionImport } from './routes/setup/point-selection'

// Create/Update Routes

const UnprojectRoute = UnprojectImport.update({
  id: '/unproject',
  path: '/unproject',
  getParentRoute: () => rootRoute,
} as any)

const Undistort2Route = Undistort2Import.update({
  id: '/undistort2',
  path: '/undistort2',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SetupIndexRoute = SetupIndexImport.update({
  id: '/setup/',
  path: '/setup/',
  getParentRoute: () => rootRoute,
} as any)

const VisualizeVisualizeCommandsRoute = VisualizeVisualizeCommandsImport.update(
  {
    id: '/visualize/VisualizeCommands',
    path: '/visualize/VisualizeCommands',
    getParentRoute: () => rootRoute,
  } as any,
)

const Visualize2DViewRoute = Visualize2DViewImport.update({
  id: '/visualize/2DView',
  path: '/visualize/2DView',
  getParentRoute: () => rootRoute,
} as any)

const SetupUrlEntryRoute = SetupUrlEntryImport.update({
  id: '/setup/url-entry',
  path: '/setup/url-entry',
  getParentRoute: () => rootRoute,
} as any)

const SetupSetupRoute = SetupSetupImport.update({
  id: '/setup/setup',
  path: '/setup/setup',
  getParentRoute: () => rootRoute,
} as any)

const SetupPointSelectionRoute = SetupPointSelectionImport.update({
  id: '/setup/point-selection',
  path: '/setup/point-selection',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/undistort2': {
      id: '/undistort2'
      path: '/undistort2'
      fullPath: '/undistort2'
      preLoaderRoute: typeof Undistort2Import
      parentRoute: typeof rootRoute
    }
    '/unproject': {
      id: '/unproject'
      path: '/unproject'
      fullPath: '/unproject'
      preLoaderRoute: typeof UnprojectImport
      parentRoute: typeof rootRoute
    }
    '/setup/point-selection': {
      id: '/setup/point-selection'
      path: '/setup/point-selection'
      fullPath: '/setup/point-selection'
      preLoaderRoute: typeof SetupPointSelectionImport
      parentRoute: typeof rootRoute
    }
    '/setup/setup': {
      id: '/setup/setup'
      path: '/setup/setup'
      fullPath: '/setup/setup'
      preLoaderRoute: typeof SetupSetupImport
      parentRoute: typeof rootRoute
    }
    '/setup/url-entry': {
      id: '/setup/url-entry'
      path: '/setup/url-entry'
      fullPath: '/setup/url-entry'
      preLoaderRoute: typeof SetupUrlEntryImport
      parentRoute: typeof rootRoute
    }
    '/visualize/2DView': {
      id: '/visualize/2DView'
      path: '/visualize/2DView'
      fullPath: '/visualize/2DView'
      preLoaderRoute: typeof Visualize2DViewImport
      parentRoute: typeof rootRoute
    }
    '/visualize/VisualizeCommands': {
      id: '/visualize/VisualizeCommands'
      path: '/visualize/VisualizeCommands'
      fullPath: '/visualize/VisualizeCommands'
      preLoaderRoute: typeof VisualizeVisualizeCommandsImport
      parentRoute: typeof rootRoute
    }
    '/setup/': {
      id: '/setup/'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/undistort2': typeof Undistort2Route
  '/unproject': typeof UnprojectRoute
  '/setup/point-selection': typeof SetupPointSelectionRoute
  '/setup/setup': typeof SetupSetupRoute
  '/setup/url-entry': typeof SetupUrlEntryRoute
  '/visualize/2DView': typeof Visualize2DViewRoute
  '/visualize/VisualizeCommands': typeof VisualizeVisualizeCommandsRoute
  '/setup': typeof SetupIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/undistort2': typeof Undistort2Route
  '/unproject': typeof UnprojectRoute
  '/setup/point-selection': typeof SetupPointSelectionRoute
  '/setup/setup': typeof SetupSetupRoute
  '/setup/url-entry': typeof SetupUrlEntryRoute
  '/visualize/2DView': typeof Visualize2DViewRoute
  '/visualize/VisualizeCommands': typeof VisualizeVisualizeCommandsRoute
  '/setup': typeof SetupIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/undistort2': typeof Undistort2Route
  '/unproject': typeof UnprojectRoute
  '/setup/point-selection': typeof SetupPointSelectionRoute
  '/setup/setup': typeof SetupSetupRoute
  '/setup/url-entry': typeof SetupUrlEntryRoute
  '/visualize/2DView': typeof Visualize2DViewRoute
  '/visualize/VisualizeCommands': typeof VisualizeVisualizeCommandsRoute
  '/setup/': typeof SetupIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/undistort2'
    | '/unproject'
    | '/setup/point-selection'
    | '/setup/setup'
    | '/setup/url-entry'
    | '/visualize/2DView'
    | '/visualize/VisualizeCommands'
    | '/setup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/undistort2'
    | '/unproject'
    | '/setup/point-selection'
    | '/setup/setup'
    | '/setup/url-entry'
    | '/visualize/2DView'
    | '/visualize/VisualizeCommands'
    | '/setup'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/undistort2'
    | '/unproject'
    | '/setup/point-selection'
    | '/setup/setup'
    | '/setup/url-entry'
    | '/visualize/2DView'
    | '/visualize/VisualizeCommands'
    | '/setup/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  Undistort2Route: typeof Undistort2Route
  UnprojectRoute: typeof UnprojectRoute
  SetupPointSelectionRoute: typeof SetupPointSelectionRoute
  SetupSetupRoute: typeof SetupSetupRoute
  SetupUrlEntryRoute: typeof SetupUrlEntryRoute
  Visualize2DViewRoute: typeof Visualize2DViewRoute
  VisualizeVisualizeCommandsRoute: typeof VisualizeVisualizeCommandsRoute
  SetupIndexRoute: typeof SetupIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  Undistort2Route: Undistort2Route,
  UnprojectRoute: UnprojectRoute,
  SetupPointSelectionRoute: SetupPointSelectionRoute,
  SetupSetupRoute: SetupSetupRoute,
  SetupUrlEntryRoute: SetupUrlEntryRoute,
  Visualize2DViewRoute: Visualize2DViewRoute,
  VisualizeVisualizeCommandsRoute: VisualizeVisualizeCommandsRoute,
  SetupIndexRoute: SetupIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/undistort2",
        "/unproject",
        "/setup/point-selection",
        "/setup/setup",
        "/setup/url-entry",
        "/visualize/2DView",
        "/visualize/VisualizeCommands",
        "/setup/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/undistort2": {
      "filePath": "undistort2.tsx"
    },
    "/unproject": {
      "filePath": "unproject.tsx"
    },
    "/setup/point-selection": {
      "filePath": "setup/point-selection.tsx"
    },
    "/setup/setup": {
      "filePath": "setup/setup.tsx"
    },
    "/setup/url-entry": {
      "filePath": "setup.url-entry.tsx"
    },
    "/visualize/2DView": {
      "filePath": "visualize/2DView.tsx"
    },
    "/visualize/VisualizeCommands": {
      "filePath": "visualize/VisualizeCommands.tsx"
    },
    "/setup/": {
      "filePath": "setup/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
