packages:
  - apps/*
  - packages/*
catalog:
  "@eslint/js": ^9.28.0
  "@hookform/devtools": ^4.4.0
  "@hookform/resolvers": ^5.0.1
  "@next/eslint-plugin-next": ^15.3.3
  "@preact/signals-react": ^3.2.0
  "@preact/signals-react-transform": ^0.5.1
  "@radix-ui/react-alert-dialog": ^1.1.14
  "@radix-ui/react-avatar": ^1.1.10
  "@radix-ui/react-checkbox": ^1.3.2
  "@radix-ui/react-collapsible": ^1.1.11
  "@radix-ui/react-dialog": ^1.1.14
  "@radix-ui/react-dropdown-menu": ^2.1.15
  "@radix-ui/react-label": ^2.1.7
  "@radix-ui/react-popover": ^1.1.14
  "@radix-ui/react-select": ^2.2.5
  "@radix-ui/react-separator": ^1.1.7
  "@radix-ui/react-slot": ^1.2.3
  "@radix-ui/react-tabs": ^1.1.12
  "@radix-ui/react-toggle": ^1.1.9
  "@radix-ui/react-tooltip": ^1.2.7
  "@react-spring/three": ^10.0.1
  "@react-spring/web": ^10.0.1
  "@react-three/drei": ^10.1.2
  "@react-three/fiber": ^9.1.2
  "@tailwindcss/vite": ^4.1.8
  "@tanstack/react-router": ^1.120.15
  "@tanstack/router": 0.0.1-beta.53
  "@tanstack/router-devtools": ^1.120.15
  "@tanstack/router-plugin": ^1.120.15
  "@tanstack/zod-adapter": ^1.120.15
  "@techstark/opencv-js": 4.10.0-release.1
  "@testing-library/dom": ^10.4.0
  "@testing-library/jest-dom": ^6.6.3
  "@testing-library/react": ^16.3.0
  "@turbo/gen": ^2.5.4
  "@types/colormap": ^2.3.4
  "@types/node": ^22.15.29
  "@types/react": ^19.1.6
  "@types/react-dom": ^19.1.5
  "@types/three": ^0.177.0
  "@types/uuid": ^10.0.0
  "@typescript-eslint/eslint-plugin": ^8.33.1
  "@typescript-eslint/parser": ^8.33.1
  "@use-gesture/react": ^10.3.1
  "@vitejs/plugin-react": ^4.5.1
  "@vitest/browser": 3.2.0
  "@vitest/coverage-v8": 3.2.0
  "@vitest/ui": 3.2.0
  "@webgpu/types": ^0.1.61
  "@zip.js/zip.js": ^2.7.62
  babel-plugin-react-compiler: 19.1.0-rc.2
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  cmdk: ^1.1.1
  colormap: ^2.3.2
  comlink: ^4.4.2
  eslint: ^9.28.0
  eslint-config-prettier: ^10.1.5
  eslint-import-resolver-typescript: ^4.4.2
  eslint-plugin-import: ^2.31.0
  eslint-plugin-jsx-a11y: ^6.10.2
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-prettier: ^5.4.1
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-refresh: ^0.4.20
  eslint-plugin-turbo: ^2.5.4
  eslint-plugin-unused-imports: ^4.1.4
  firebase: ^11.8.1
  gcode-toolpath: ^3.0.0
  globals: ^16.2.0
  immer: ^10.1.1
  jotai: ^2.12.5
  jsdom: ^26.1.0
  konva: ^9.3.20
  loglevel: ^1.9.2
  lucide-react: ^0.511.0
  mathjs: ^14.5.2
  mitt: ^3.0.1
  motion: ^12.16.0
  next-qrcode: ^2.5.1
  next-themes: ^0.4.6
  playwright: ^1.52.0
  prettier: ^3.5.3
  react: ^19.1.0
  react-device-detect: ^2.2.3
  react-dom: ^19.1.0
  react-dropzone: ^14.3.8
  react-error-boundary: ^6.0.0
  react-hook-form: ^7.57.0
  react-hotkeys-hook: ^5.1.0
  react-konva: ^19.0.4
  react-number-format: ^5.4.4
  react-zoom-pan-pinch: ^3.7.0
  serve: ^14.2.4
  sonner: ^2.0.5
  superjson: ^2.2.2
  suspend-react: ^0.1.3
  tailwind-merge: ^3.3.0
  tailwindcss: ^4.1.8
  tailwindcss-animate: ^1.0.7
  three: ^0.177.0
  three-stdlib: ^2.36.0
  trystero: ^0.21.5
  ts-node: ^10.9.2
  turbo: ^2.5.4
  tw-animate-css: ^1.3.3
  typescript-eslint: ^8.33.1
  uuid: ^11.1.0
  vite: ^6.3.5
  vite-plugin-checker: ^0.9.3
  vite-plugin-node-polyfills: ^0.23.0
  vite-plugin-singlefile: ^2.2.0
  vite-tsconfig-paths: ^5.1.4
  vitest: 3.2.0
  vitest-browser-react: ^0.2.0
  yaml: ^2.8.0
  zod: ^3.25.49
  zustand: ^5.0.5
