/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SetupIndexRouteImport } from './routes/setup/index'
import { Route as VisualizeVisualizeCommandsRouteImport } from './routes/visualize/VisualizeCommands'
import { Route as Visualize2DViewRouteImport } from './routes/visualize/2DView'
import { Route as SetupUrlEntryRouteImport } from './routes/setup/url-entry'
import { Route as SetupPointSelectionRouteImport } from './routes/setup/point-selection'
import { Route as SetupNewCamMatrixRouteImport } from './routes/setup/new-cam-matrix'
import { Route as SetupMarkerPositionsRouteImport } from './routes/setup/marker-positions'
import { Route as SetupMachineBoundsRouteImport } from './routes/setup/machine-bounds'
import { Route as SetupFluidncRouteImport } from './routes/setup/fluidnc'
import { Route as SetupEditSettingsRouteImport } from './routes/setup/edit-settings'
import { Route as SetupCameraCalibrationRouteImport } from './routes/setup/camera-calibration'
import { Route as SettingsHideMachineRouteImport } from './routes/settings/hide-machine'
import { Route as DebugUnprojectRouteImport } from './routes/debug/unproject'
import { Route as DebugUndistort2RouteImport } from './routes/debug/undistort2'
import { Route as DebugRawWebgpuRouteImport } from './routes/debug/raw-webgpu'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupIndexRoute = SetupIndexRouteImport.update({
  id: '/setup/',
  path: '/setup/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualizeVisualizeCommandsRoute =
  VisualizeVisualizeCommandsRouteImport.update({
    id: '/visualize/VisualizeCommands',
    path: '/visualize/VisualizeCommands',
    getParentRoute: () => rootRouteImport,
  } as any)
const Visualize2DViewRoute = Visualize2DViewRouteImport.update({
  id: '/visualize/2DView',
  path: '/visualize/2DView',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupUrlEntryRoute = SetupUrlEntryRouteImport.update({
  id: '/setup/url-entry',
  path: '/setup/url-entry',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupPointSelectionRoute = SetupPointSelectionRouteImport.update({
  id: '/setup/point-selection',
  path: '/setup/point-selection',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupNewCamMatrixRoute = SetupNewCamMatrixRouteImport.update({
  id: '/setup/new-cam-matrix',
  path: '/setup/new-cam-matrix',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupMarkerPositionsRoute = SetupMarkerPositionsRouteImport.update({
  id: '/setup/marker-positions',
  path: '/setup/marker-positions',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupMachineBoundsRoute = SetupMachineBoundsRouteImport.update({
  id: '/setup/machine-bounds',
  path: '/setup/machine-bounds',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupFluidncRoute = SetupFluidncRouteImport.update({
  id: '/setup/fluidnc',
  path: '/setup/fluidnc',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupEditSettingsRoute = SetupEditSettingsRouteImport.update({
  id: '/setup/edit-settings',
  path: '/setup/edit-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupCameraCalibrationRoute = SetupCameraCalibrationRouteImport.update({
  id: '/setup/camera-calibration',
  path: '/setup/camera-calibration',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsHideMachineRoute = SettingsHideMachineRouteImport.update({
  id: '/settings/hide-machine',
  path: '/settings/hide-machine',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugUnprojectRoute = DebugUnprojectRouteImport.update({
  id: '/debug/unproject',
  path: '/debug/unproject',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugUndistort2Route = DebugUndistort2RouteImport.update({
  id: '/debug/undistort2',
  path: '/debug/undistort2',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRawWebgpuRoute = DebugRawWebgpuRouteImport.update({
  id: '/debug/raw-webgpu',
  path: '/debug/raw-webgpu',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/debug/raw-webgpu': typeof DebugRawWebgpuRoute
  '/debug/undistort2': typeof DebugUndistort2Route
  '/debug/unproject': typeof DebugUnprojectRoute
  '/settings/hide-machine': typeof SettingsHideMachineRoute
  '/setup/camera-calibration': typeof SetupCameraCalibrationRoute
  '/setup/edit-settings': typeof SetupEditSettingsRoute
  '/setup/fluidnc': typeof SetupFluidncRoute
  '/setup/machine-bounds': typeof SetupMachineBoundsRoute
  '/setup/marker-positions': typeof SetupMarkerPositionsRoute
  '/setup/new-cam-matrix': typeof SetupNewCamMatrixRoute
  '/setup/point-selection': typeof SetupPointSelectionRoute
  '/setup/url-entry': typeof SetupUrlEntryRoute
  '/visualize/2DView': typeof Visualize2DViewRoute
  '/visualize/VisualizeCommands': typeof VisualizeVisualizeCommandsRoute
  '/setup': typeof SetupIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/debug/raw-webgpu': typeof DebugRawWebgpuRoute
  '/debug/undistort2': typeof DebugUndistort2Route
  '/debug/unproject': typeof DebugUnprojectRoute
  '/settings/hide-machine': typeof SettingsHideMachineRoute
  '/setup/camera-calibration': typeof SetupCameraCalibrationRoute
  '/setup/edit-settings': typeof SetupEditSettingsRoute
  '/setup/fluidnc': typeof SetupFluidncRoute
  '/setup/machine-bounds': typeof SetupMachineBoundsRoute
  '/setup/marker-positions': typeof SetupMarkerPositionsRoute
  '/setup/new-cam-matrix': typeof SetupNewCamMatrixRoute
  '/setup/point-selection': typeof SetupPointSelectionRoute
  '/setup/url-entry': typeof SetupUrlEntryRoute
  '/visualize/2DView': typeof Visualize2DViewRoute
  '/visualize/VisualizeCommands': typeof VisualizeVisualizeCommandsRoute
  '/setup': typeof SetupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/debug/raw-webgpu': typeof DebugRawWebgpuRoute
  '/debug/undistort2': typeof DebugUndistort2Route
  '/debug/unproject': typeof DebugUnprojectRoute
  '/settings/hide-machine': typeof SettingsHideMachineRoute
  '/setup/camera-calibration': typeof SetupCameraCalibrationRoute
  '/setup/edit-settings': typeof SetupEditSettingsRoute
  '/setup/fluidnc': typeof SetupFluidncRoute
  '/setup/machine-bounds': typeof SetupMachineBoundsRoute
  '/setup/marker-positions': typeof SetupMarkerPositionsRoute
  '/setup/new-cam-matrix': typeof SetupNewCamMatrixRoute
  '/setup/point-selection': typeof SetupPointSelectionRoute
  '/setup/url-entry': typeof SetupUrlEntryRoute
  '/visualize/2DView': typeof Visualize2DViewRoute
  '/visualize/VisualizeCommands': typeof VisualizeVisualizeCommandsRoute
  '/setup/': typeof SetupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/debug/raw-webgpu'
    | '/debug/undistort2'
    | '/debug/unproject'
    | '/settings/hide-machine'
    | '/setup/camera-calibration'
    | '/setup/edit-settings'
    | '/setup/fluidnc'
    | '/setup/machine-bounds'
    | '/setup/marker-positions'
    | '/setup/new-cam-matrix'
    | '/setup/point-selection'
    | '/setup/url-entry'
    | '/visualize/2DView'
    | '/visualize/VisualizeCommands'
    | '/setup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/debug/raw-webgpu'
    | '/debug/undistort2'
    | '/debug/unproject'
    | '/settings/hide-machine'
    | '/setup/camera-calibration'
    | '/setup/edit-settings'
    | '/setup/fluidnc'
    | '/setup/machine-bounds'
    | '/setup/marker-positions'
    | '/setup/new-cam-matrix'
    | '/setup/point-selection'
    | '/setup/url-entry'
    | '/visualize/2DView'
    | '/visualize/VisualizeCommands'
    | '/setup'
  id:
    | '__root__'
    | '/'
    | '/debug/raw-webgpu'
    | '/debug/undistort2'
    | '/debug/unproject'
    | '/settings/hide-machine'
    | '/setup/camera-calibration'
    | '/setup/edit-settings'
    | '/setup/fluidnc'
    | '/setup/machine-bounds'
    | '/setup/marker-positions'
    | '/setup/new-cam-matrix'
    | '/setup/point-selection'
    | '/setup/url-entry'
    | '/visualize/2DView'
    | '/visualize/VisualizeCommands'
    | '/setup/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DebugRawWebgpuRoute: typeof DebugRawWebgpuRoute
  DebugUndistort2Route: typeof DebugUndistort2Route
  DebugUnprojectRoute: typeof DebugUnprojectRoute
  SettingsHideMachineRoute: typeof SettingsHideMachineRoute
  SetupCameraCalibrationRoute: typeof SetupCameraCalibrationRoute
  SetupEditSettingsRoute: typeof SetupEditSettingsRoute
  SetupFluidncRoute: typeof SetupFluidncRoute
  SetupMachineBoundsRoute: typeof SetupMachineBoundsRoute
  SetupMarkerPositionsRoute: typeof SetupMarkerPositionsRoute
  SetupNewCamMatrixRoute: typeof SetupNewCamMatrixRoute
  SetupPointSelectionRoute: typeof SetupPointSelectionRoute
  SetupUrlEntryRoute: typeof SetupUrlEntryRoute
  Visualize2DViewRoute: typeof Visualize2DViewRoute
  VisualizeVisualizeCommandsRoute: typeof VisualizeVisualizeCommandsRoute
  SetupIndexRoute: typeof SetupIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/': {
      id: '/setup/'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visualize/VisualizeCommands': {
      id: '/visualize/VisualizeCommands'
      path: '/visualize/VisualizeCommands'
      fullPath: '/visualize/VisualizeCommands'
      preLoaderRoute: typeof VisualizeVisualizeCommandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visualize/2DView': {
      id: '/visualize/2DView'
      path: '/visualize/2DView'
      fullPath: '/visualize/2DView'
      preLoaderRoute: typeof Visualize2DViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/url-entry': {
      id: '/setup/url-entry'
      path: '/setup/url-entry'
      fullPath: '/setup/url-entry'
      preLoaderRoute: typeof SetupUrlEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/point-selection': {
      id: '/setup/point-selection'
      path: '/setup/point-selection'
      fullPath: '/setup/point-selection'
      preLoaderRoute: typeof SetupPointSelectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/new-cam-matrix': {
      id: '/setup/new-cam-matrix'
      path: '/setup/new-cam-matrix'
      fullPath: '/setup/new-cam-matrix'
      preLoaderRoute: typeof SetupNewCamMatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/marker-positions': {
      id: '/setup/marker-positions'
      path: '/setup/marker-positions'
      fullPath: '/setup/marker-positions'
      preLoaderRoute: typeof SetupMarkerPositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/machine-bounds': {
      id: '/setup/machine-bounds'
      path: '/setup/machine-bounds'
      fullPath: '/setup/machine-bounds'
      preLoaderRoute: typeof SetupMachineBoundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/fluidnc': {
      id: '/setup/fluidnc'
      path: '/setup/fluidnc'
      fullPath: '/setup/fluidnc'
      preLoaderRoute: typeof SetupFluidncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/edit-settings': {
      id: '/setup/edit-settings'
      path: '/setup/edit-settings'
      fullPath: '/setup/edit-settings'
      preLoaderRoute: typeof SetupEditSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/camera-calibration': {
      id: '/setup/camera-calibration'
      path: '/setup/camera-calibration'
      fullPath: '/setup/camera-calibration'
      preLoaderRoute: typeof SetupCameraCalibrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/hide-machine': {
      id: '/settings/hide-machine'
      path: '/settings/hide-machine'
      fullPath: '/settings/hide-machine'
      preLoaderRoute: typeof SettingsHideMachineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/unproject': {
      id: '/debug/unproject'
      path: '/debug/unproject'
      fullPath: '/debug/unproject'
      preLoaderRoute: typeof DebugUnprojectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/undistort2': {
      id: '/debug/undistort2'
      path: '/debug/undistort2'
      fullPath: '/debug/undistort2'
      preLoaderRoute: typeof DebugUndistort2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/raw-webgpu': {
      id: '/debug/raw-webgpu'
      path: '/debug/raw-webgpu'
      fullPath: '/debug/raw-webgpu'
      preLoaderRoute: typeof DebugRawWebgpuRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DebugRawWebgpuRoute: DebugRawWebgpuRoute,
  DebugUndistort2Route: DebugUndistort2Route,
  DebugUnprojectRoute: DebugUnprojectRoute,
  SettingsHideMachineRoute: SettingsHideMachineRoute,
  SetupCameraCalibrationRoute: SetupCameraCalibrationRoute,
  SetupEditSettingsRoute: SetupEditSettingsRoute,
  SetupFluidncRoute: SetupFluidncRoute,
  SetupMachineBoundsRoute: SetupMachineBoundsRoute,
  SetupMarkerPositionsRoute: SetupMarkerPositionsRoute,
  SetupNewCamMatrixRoute: SetupNewCamMatrixRoute,
  SetupPointSelectionRoute: SetupPointSelectionRoute,
  SetupUrlEntryRoute: SetupUrlEntryRoute,
  Visualize2DViewRoute: Visualize2DViewRoute,
  VisualizeVisualizeCommandsRoute: VisualizeVisualizeCommandsRoute,
  SetupIndexRoute: SetupIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
