/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as Go2webrtcImport } from './routes/go2webrtc'

// Create/Update Routes

const Go2webrtcRoute = Go2webrtcImport.update({
  id: '/go2webrtc',
  path: '/go2webrtc',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/go2webrtc': {
      id: '/go2webrtc'
      path: '/go2webrtc'
      fullPath: '/go2webrtc'
      preLoaderRoute: typeof Go2webrtcImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/go2webrtc': typeof Go2webrtcRoute
}

export interface FileRoutesByTo {
  '/go2webrtc': typeof Go2webrtcRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/go2webrtc': typeof Go2webrtcRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/go2webrtc'
  fileRoutesByTo: FileRoutesByTo
  to: '/go2webrtc'
  id: '__root__' | '/go2webrtc'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  Go2webrtcRoute: typeof Go2webrtcRoute
}

const rootRouteChildren: RootRouteChildren = {
  Go2webrtcRoute: Go2webrtcRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/go2webrtc"
      ]
    },
    "/go2webrtc": {
      "filePath": "go2webrtc.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
