/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServeWebrtcRouteImport } from './routes/serve-webrtc'
import { Route as ServeTrysteroRouteImport } from './routes/serve-trystero'
import { Route as PlayTrysteroRouteImport } from './routes/play-trystero'
import { Route as Go2webrtcRouteImport } from './routes/go2webrtc'
import { Route as CameraCalibrationRouteImport } from './routes/camera-calibration'
import { Route as WebrtcChannelRoomRouteImport } from './routes/webrtc-channel.$room'
import { Route as FluidncClientRoomIdRouteImport } from './routes/fluidnc-client.$roomId'

const ServeWebrtcRoute = ServeWebrtcRouteImport.update({
  id: '/serve-webrtc',
  path: '/serve-webrtc',
  getParentRoute: () => rootRouteImport,
} as any)
const ServeTrysteroRoute = ServeTrysteroRouteImport.update({
  id: '/serve-trystero',
  path: '/serve-trystero',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayTrysteroRoute = PlayTrysteroRouteImport.update({
  id: '/play-trystero',
  path: '/play-trystero',
  getParentRoute: () => rootRouteImport,
} as any)
const Go2webrtcRoute = Go2webrtcRouteImport.update({
  id: '/go2webrtc',
  path: '/go2webrtc',
  getParentRoute: () => rootRouteImport,
} as any)
const CameraCalibrationRoute = CameraCalibrationRouteImport.update({
  id: '/camera-calibration',
  path: '/camera-calibration',
  getParentRoute: () => rootRouteImport,
} as any)
const WebrtcChannelRoomRoute = WebrtcChannelRoomRouteImport.update({
  id: '/webrtc-channel/$room',
  path: '/webrtc-channel/$room',
  getParentRoute: () => rootRouteImport,
} as any)
const FluidncClientRoomIdRoute = FluidncClientRoomIdRouteImport.update({
  id: '/fluidnc-client/$roomId',
  path: '/fluidnc-client/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/camera-calibration': typeof CameraCalibrationRoute
  '/go2webrtc': typeof Go2webrtcRoute
  '/play-trystero': typeof PlayTrysteroRoute
  '/serve-trystero': typeof ServeTrysteroRoute
  '/serve-webrtc': typeof ServeWebrtcRoute
  '/fluidnc-client/$roomId': typeof FluidncClientRoomIdRoute
  '/webrtc-channel/$room': typeof WebrtcChannelRoomRoute
}
export interface FileRoutesByTo {
  '/camera-calibration': typeof CameraCalibrationRoute
  '/go2webrtc': typeof Go2webrtcRoute
  '/play-trystero': typeof PlayTrysteroRoute
  '/serve-trystero': typeof ServeTrysteroRoute
  '/serve-webrtc': typeof ServeWebrtcRoute
  '/fluidnc-client/$roomId': typeof FluidncClientRoomIdRoute
  '/webrtc-channel/$room': typeof WebrtcChannelRoomRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/camera-calibration': typeof CameraCalibrationRoute
  '/go2webrtc': typeof Go2webrtcRoute
  '/play-trystero': typeof PlayTrysteroRoute
  '/serve-trystero': typeof ServeTrysteroRoute
  '/serve-webrtc': typeof ServeWebrtcRoute
  '/fluidnc-client/$roomId': typeof FluidncClientRoomIdRoute
  '/webrtc-channel/$room': typeof WebrtcChannelRoomRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/camera-calibration'
    | '/go2webrtc'
    | '/play-trystero'
    | '/serve-trystero'
    | '/serve-webrtc'
    | '/fluidnc-client/$roomId'
    | '/webrtc-channel/$room'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/camera-calibration'
    | '/go2webrtc'
    | '/play-trystero'
    | '/serve-trystero'
    | '/serve-webrtc'
    | '/fluidnc-client/$roomId'
    | '/webrtc-channel/$room'
  id:
    | '__root__'
    | '/camera-calibration'
    | '/go2webrtc'
    | '/play-trystero'
    | '/serve-trystero'
    | '/serve-webrtc'
    | '/fluidnc-client/$roomId'
    | '/webrtc-channel/$room'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CameraCalibrationRoute: typeof CameraCalibrationRoute
  Go2webrtcRoute: typeof Go2webrtcRoute
  PlayTrysteroRoute: typeof PlayTrysteroRoute
  ServeTrysteroRoute: typeof ServeTrysteroRoute
  ServeWebrtcRoute: typeof ServeWebrtcRoute
  FluidncClientRoomIdRoute: typeof FluidncClientRoomIdRoute
  WebrtcChannelRoomRoute: typeof WebrtcChannelRoomRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/serve-webrtc': {
      id: '/serve-webrtc'
      path: '/serve-webrtc'
      fullPath: '/serve-webrtc'
      preLoaderRoute: typeof ServeWebrtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/serve-trystero': {
      id: '/serve-trystero'
      path: '/serve-trystero'
      fullPath: '/serve-trystero'
      preLoaderRoute: typeof ServeTrysteroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play-trystero': {
      id: '/play-trystero'
      path: '/play-trystero'
      fullPath: '/play-trystero'
      preLoaderRoute: typeof PlayTrysteroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go2webrtc': {
      id: '/go2webrtc'
      path: '/go2webrtc'
      fullPath: '/go2webrtc'
      preLoaderRoute: typeof Go2webrtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camera-calibration': {
      id: '/camera-calibration'
      path: '/camera-calibration'
      fullPath: '/camera-calibration'
      preLoaderRoute: typeof CameraCalibrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webrtc-channel/$room': {
      id: '/webrtc-channel/$room'
      path: '/webrtc-channel/$room'
      fullPath: '/webrtc-channel/$room'
      preLoaderRoute: typeof WebrtcChannelRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fluidnc-client/$roomId': {
      id: '/fluidnc-client/$roomId'
      path: '/fluidnc-client/$roomId'
      fullPath: '/fluidnc-client/$roomId'
      preLoaderRoute: typeof FluidncClientRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  CameraCalibrationRoute: CameraCalibrationRoute,
  Go2webrtcRoute: Go2webrtcRoute,
  PlayTrysteroRoute: PlayTrysteroRoute,
  ServeTrysteroRoute: ServeTrysteroRoute,
  ServeWebrtcRoute: ServeWebrtcRoute,
  FluidncClientRoomIdRoute: FluidncClientRoomIdRoute,
  WebrtcChannelRoomRoute: WebrtcChannelRoomRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
