/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WebtorrentImport } from './routes/webtorrent'

// Create/Update Routes

const WebtorrentRoute = WebtorrentImport.update({
  id: '/webtorrent',
  path: '/webtorrent',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/webtorrent': {
      id: '/webtorrent'
      path: '/webtorrent'
      fullPath: '/webtorrent'
      preLoaderRoute: typeof WebtorrentImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/webtorrent': typeof WebtorrentRoute
}

export interface FileRoutesByTo {
  '/webtorrent': typeof WebtorrentRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/webtorrent': typeof WebtorrentRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/webtorrent'
  fileRoutesByTo: FileRoutesByTo
  to: '/webtorrent'
  id: '__root__' | '/webtorrent'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  WebtorrentRoute: typeof WebtorrentRoute
}

const rootRouteChildren: RootRouteChildren = {
  WebtorrentRoute: WebtorrentRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/webtorrent"
      ]
    },
    "/webtorrent": {
      "filePath": "webtorrent.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
