/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as VisualizeImport } from './routes/visualize'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as SetupIndexImport } from './routes/setup/index'
import { Route as SetupUrlEntryImport } from './routes/setup.url-entry'
import { Route as SetupSetupImport } from './routes/setup/setup'
import { Route as SetupPointSelectionImport } from './routes/setup/point-selection'
import { Route as SetupSetupPointSelectionImport } from './routes/setup/setup.point-selection'

// Create/Update Routes

const VisualizeRoute = VisualizeImport.update({
  id: '/visualize',
  path: '/visualize',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SetupIndexRoute = SetupIndexImport.update({
  id: '/setup/',
  path: '/setup/',
  getParentRoute: () => rootRoute,
} as any)

const SetupUrlEntryRoute = SetupUrlEntryImport.update({
  id: '/setup/url-entry',
  path: '/setup/url-entry',
  getParentRoute: () => rootRoute,
} as any)

const SetupSetupRoute = SetupSetupImport.update({
  id: '/setup/setup',
  path: '/setup/setup',
  getParentRoute: () => rootRoute,
} as any)

const SetupPointSelectionRoute = SetupPointSelectionImport.update({
  id: '/setup/point-selection',
  path: '/setup/point-selection',
  getParentRoute: () => rootRoute,
} as any)

const SetupSetupPointSelectionRoute = SetupSetupPointSelectionImport.update({
  id: '/point-selection',
  path: '/point-selection',
  getParentRoute: () => SetupSetupRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/visualize': {
      id: '/visualize'
      path: '/visualize'
      fullPath: '/visualize'
      preLoaderRoute: typeof VisualizeImport
      parentRoute: typeof rootRoute
    }
    '/setup/point-selection': {
      id: '/setup/point-selection'
      path: '/setup/point-selection'
      fullPath: '/setup/point-selection'
      preLoaderRoute: typeof SetupPointSelectionImport
      parentRoute: typeof rootRoute
    }
    '/setup/setup': {
      id: '/setup/setup'
      path: '/setup/setup'
      fullPath: '/setup/setup'
      preLoaderRoute: typeof SetupSetupImport
      parentRoute: typeof rootRoute
    }
    '/setup/url-entry': {
      id: '/setup/url-entry'
      path: '/setup/url-entry'
      fullPath: '/setup/url-entry'
      preLoaderRoute: typeof SetupUrlEntryImport
      parentRoute: typeof rootRoute
    }
    '/setup/': {
      id: '/setup/'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupIndexImport
      parentRoute: typeof rootRoute
    }
    '/setup/setup/point-selection': {
      id: '/setup/setup/point-selection'
      path: '/point-selection'
      fullPath: '/setup/setup/point-selection'
      preLoaderRoute: typeof SetupSetupPointSelectionImport
      parentRoute: typeof SetupSetupImport
    }
  }
}

// Create and export the route tree

interface SetupSetupRouteChildren {
  SetupSetupPointSelectionRoute: typeof SetupSetupPointSelectionRoute
}

const SetupSetupRouteChildren: SetupSetupRouteChildren = {
  SetupSetupPointSelectionRoute: SetupSetupPointSelectionRoute,
}

const SetupSetupRouteWithChildren = SetupSetupRoute._addFileChildren(
  SetupSetupRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/visualize': typeof VisualizeRoute
  '/setup/point-selection': typeof SetupPointSelectionRoute
  '/setup/setup': typeof SetupSetupRouteWithChildren
  '/setup/url-entry': typeof SetupUrlEntryRoute
  '/setup': typeof SetupIndexRoute
  '/setup/setup/point-selection': typeof SetupSetupPointSelectionRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/visualize': typeof VisualizeRoute
  '/setup/point-selection': typeof SetupPointSelectionRoute
  '/setup/setup': typeof SetupSetupRouteWithChildren
  '/setup/url-entry': typeof SetupUrlEntryRoute
  '/setup': typeof SetupIndexRoute
  '/setup/setup/point-selection': typeof SetupSetupPointSelectionRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/visualize': typeof VisualizeRoute
  '/setup/point-selection': typeof SetupPointSelectionRoute
  '/setup/setup': typeof SetupSetupRouteWithChildren
  '/setup/url-entry': typeof SetupUrlEntryRoute
  '/setup/': typeof SetupIndexRoute
  '/setup/setup/point-selection': typeof SetupSetupPointSelectionRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/visualize'
    | '/setup/point-selection'
    | '/setup/setup'
    | '/setup/url-entry'
    | '/setup'
    | '/setup/setup/point-selection'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/visualize'
    | '/setup/point-selection'
    | '/setup/setup'
    | '/setup/url-entry'
    | '/setup'
    | '/setup/setup/point-selection'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/visualize'
    | '/setup/point-selection'
    | '/setup/setup'
    | '/setup/url-entry'
    | '/setup/'
    | '/setup/setup/point-selection'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  VisualizeRoute: typeof VisualizeRoute
  SetupPointSelectionRoute: typeof SetupPointSelectionRoute
  SetupSetupRoute: typeof SetupSetupRouteWithChildren
  SetupUrlEntryRoute: typeof SetupUrlEntryRoute
  SetupIndexRoute: typeof SetupIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  VisualizeRoute: VisualizeRoute,
  SetupPointSelectionRoute: SetupPointSelectionRoute,
  SetupSetupRoute: SetupSetupRouteWithChildren,
  SetupUrlEntryRoute: SetupUrlEntryRoute,
  SetupIndexRoute: SetupIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/visualize",
        "/setup/point-selection",
        "/setup/setup",
        "/setup/url-entry",
        "/setup/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/visualize": {
      "filePath": "visualize.tsx"
    },
    "/setup/point-selection": {
      "filePath": "setup/point-selection.tsx"
    },
    "/setup/setup": {
      "filePath": "setup/setup.tsx",
      "children": [
        "/setup/setup/point-selection"
      ]
    },
    "/setup/url-entry": {
      "filePath": "setup.url-entry.tsx"
    },
    "/setup/": {
      "filePath": "setup/index.tsx"
    },
    "/setup/setup/point-selection": {
      "filePath": "setup/setup.point-selection.tsx",
      "parent": "/setup/setup"
    }
  }
}
ROUTE_MANIFEST_END */
